name: iOS CI 3 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-15

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Select correct Xcode version
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.4.app

      - name: List Simulators
        run: xcrun simctl list

      # 3. Show folder structure (debug)
      - name: Debug folder structure
        run: ls -R .

      - name: Boot Simulator
        run: | 
          xcrun simctl boot "iPhone 16"
          
      # 4. Build and test using xcodebuild
      - name: Build and Test
        run: |
          xcodebuild \
            -project "login-uikit-ui-testing.xcodeproj" \
            -scheme "login-uikit-ui-testing" \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.5' \
            -resultBundlePath TestResults.xcresult \
            clean test | xcpretty --report junit

      # 5. Upload artifacts so you can inspect screenshots, logs, etc.
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: TestResults.xcresult
          retention-days: 7
